name: Build and Release

on:
    push:
        branches:
            - main
        paths:
            - "tools/imports/**"

    # Manual trigger
    workflow_dispatch:

permissions:
    contents: write # Allow the action to write to the repository (for creating tags/releases)
    discussions: read # Optional, adjust according to your needs

jobs:
    build:
        runs-on: ubuntu-latest

        concurrency:
            group: build-and-release-${{ github.ref }}
            cancel-in-progress: true

        steps:
            # Step 1: Checkout the code
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Fetch all history for changelog generation

            # Step 2: Install GitHub CLI (gh)
            - name: Install GitHub CLI
              run: sudo apt-get install gh -y

            # Step 3: Set Version from Git Tags
            - name: Set Version from Git Tags
              id: set_version
              run: |
                  # Fetch all tags to ensure we have the latest version information
                  git fetch --tags
                  
                  # Get the latest semantic version tag (v*.*.*)
                  LATEST_TAG=$(git tag -l "v*.*.*" | sort -V | tail -1)

                  if [ -z "$LATEST_TAG" ]; then
                    # If no semantic version tags exist, start with v1.0.1
                    NEW_VERSION="1.0.1"
                    echo "No semantic version tags found, starting with v1.0.1"
                  else
                    echo "Latest semantic version tag found: $LATEST_TAG"
                    # Increment the patch version of the last tag
                    # Remove 'v' prefix for version manipulation
                    LATEST_VERSION=${LATEST_TAG#v}
                    
                    # Split version into parts
                    MAJOR=$(echo $LATEST_VERSION | cut -d. -f1)
                    MINOR=$(echo $LATEST_VERSION | cut -d. -f2)
                    PATCH=$(echo $LATEST_VERSION | cut -d. -f3)
                    
                    # Increment patch version
                    NEW_PATCH=$((PATCH + 1))
                    
                    # Assemble new version string
                    NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
                  fi
                  
                  echo "TAG=v$NEW_VERSION" >> $GITHUB_ENV
                  echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
                  echo "ZIP_NAME=QuaziiUI_MoP_Classic-v$NEW_VERSION.zip" >> $GITHUB_ENV
                  echo "Latest semantic version tag was: $LATEST_TAG"
                  echo "New version will be: v$NEW_VERSION"
            
            # Step 4: Ensure the version matches the release tag in the .toc file
            - name: Update version in .toc file
              run: |
                  echo "Debug: Updating .toc version to ${{ env.NEW_VERSION }}."
                  # Update main .toc file
                  sed -i "s/@project-version@/${{ env.NEW_VERSION }}/g" "./QuaziiUI_MoP_Classic/QuaziiUI_MoP_Classic.toc"
                  # Update MoP Classic specific .toc file
                  sed -i "s/@project-version@/${{ env.NEW_VERSION }}/g" "./QuaziiUI_MoP_Classic/QuaziiUI_MoP_Classic_Mists.toc"

            # Step 5: Run build.py
            - name: Run build.py
              run: python tools/build.py

            # Step 6: Zip the QuaziiUI_MoP_Classic directory
            - name: Zip QuaziiUI_MoP_Classic directory
              run: |
                  echo "Debug: Zipping QuaziiUI_MoP_Classic directory to ${{ env.ZIP_NAME }}"
                  zip -r ${{ env.ZIP_NAME }} QuaziiUI_MoP_Classic

            # Step 7: Generate changelog
            - name: Generate changelog
              run: |
                  # Get the latest semantic version tag (v*.*.*)
                  LAST_TAG=$(git tag -l "v*.*.*" | sort -V | tail -1)
                  
                  # Check if there are any semantic version tags
                  if [ -n "$LAST_TAG" ]; then
                      echo "Debug: Last semantic version tag found: $LAST_TAG"
                      echo "Changes since $LAST_TAG:" > CHANGELOG.md
                      git log $LAST_TAG..HEAD --oneline >> CHANGELOG.md
                  else
                      # If no semantic version tags exist, generate changelog for all commits
                      echo "Debug: No semantic version tags found, generating changelog for all commits."
                      echo "Changes since the beginning:" > CHANGELOG.md
                      git log --oneline >> CHANGELOG.md
                  fi

            - name: Output changelog
              id: changelog
              run: |
                  echo "Debug: Generated changelog content"
                  cat CHANGELOG.md

            # Step 8: Create GitHub Release
            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  echo "Debug: Creating release for tag ${{ env.TAG }}"
                  gh release create ${{ env.TAG }} \
                    ${{ env.ZIP_NAME }} \
                    --title "QuaziiUI_MoP_Classic ${{ env.TAG }}" \
                    --notes-file CHANGELOG.md \
                    --target main

            # Step 9: Clean up temporary files
            - name: Clean up temporary files
              run: |
                  echo "Debug: Cleaning up temporary files"
                  rm -f ${{ env.ZIP_NAME }}
                  rm -f CHANGELOG.md
